name: Publish

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        type: boolean
        required: false
        default: 'false'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: publish crates
      uses: katyo/publish-crates@v2
      with:
        dry-run: ${{ github.event.inputs.dry-run == 'true' }}
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        path: './crates/app-state'
